<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Edvaniq.Services.Analytics.Domain\Edvaniq.Services.Analytics.Domain.csproj" />
    <ProjectReference Include="..\Edvaniq.Services.Analytics.Contracts\Edvaniq.Services.Analytics.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Edvaniq.BuildingBlocks.Application\Edvaniq.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Identity\Edvaniq.Services.Identity.Contracts\Edvaniq.Services.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Planning\Edvaniq.Services.Planning.Contracts\Edvaniq.Services.Planning.Contracts.csproj" />
    <ProjectReference Include="..\..\Assessment\Edvaniq.Services.Assessment.Contracts\Edvaniq.Services.Assessment.Contracts.csproj" />
    <ProjectReference Include="..\..\Flashcards\Edvaniq.Services.Flashcards.Contracts\Edvaniq.Services.Flashcards.Contracts.csproj" />
    <ProjectReference Include="..\..\LearningEngine\Edvaniq.Services.LearningEngine.Contracts\Edvaniq.Services.LearningEngine.Contracts.csproj" />
    <ProjectReference Include="..\..\Gamification\Edvaniq.Services.Gamification.Contracts\Edvaniq.Services.Gamification.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
