<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Edvaniq.Services.Identity.Application\Edvaniq.Services.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Edvaniq.BuildingBlocks.Infrastructure\Edvaniq.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Edvaniq.BuildingBlocks.Messaging\Edvaniq.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
