<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>dotnet-Edvaniq.Services.Notifications.Worker-5c719612-8149-4e9e-ba56-a5c3c7c17e1b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edvaniq.Services.Notifications.Application\Edvaniq.Services.Notifications.Application.csproj" />
    <ProjectReference Include="..\Edvaniq.Services.Notifications.Infrastructure\Edvaniq.Services.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Aspire\Edvaniq.ServiceDefaults\Edvaniq.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
